version: '3.4'

services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Pass@word
  basicredisleaderboarddemodotnetcore:
    image: ${DOCKER_REGISTRY-}basicredisleaderboarddemodotnetcore
    build:
      context: .
      dockerfile: BasicRedisLeaderboardDemoDotNetCore/Dockerfile
    environment:
      - ConnectionStrings__ConnectionString=sql;database=TestDb;User Id=sa;Password=Pass@word